### PR TITLE
A lot of changes.

### PR DESCRIPTION
**Pull request by jeremy-wendt**

### CODE REVIEW

**Comment by jbasilico** [comment]
I'm seeing the following error trying to run the tests for Common Core: 
```
createMatrices(gov.sandia.cognition.math.matrix.optimized.ConstructorTest)  Time elapsed: 0.007 sec  <<< ERROR!
java.lang.IllegalStateException: This code has errors.
	at sun.reflect.UnsafeFieldAccessorImpl.throwFinalFieldIllegalAccessException(UnsafeFieldAccessorImpl.java:73)
	at sun.reflect.UnsafeFieldAccessorImpl.throwFinalFieldIllegalAccessException(UnsafeFieldAccessorImpl.java:77)
	at sun.reflect.UnsafeQualifiedStaticObjectFieldAccessorImpl.set(UnsafeQualifiedStaticObjectFieldAccessorImpl.java:77)
	at java.lang.reflect.Field.set(Field.java:741)
	at gov.sandia.cognition.math.matrix.optimized.NativeBlasHandler.setToJBlas(NativeBlasHandler.java:144)
	at gov.sandia.cognition.math.matrix.optimized.DenseMatrix.initBlas(DenseMatrix.java:235)
	at gov.sandia.cognition.math.matrix.optimized.DenseMatrix.<init>(DenseMatrix.java:57)
	at gov.sandia.cognition.math.matrix.optimized.ConstructorTest.createMatrices(ConstructorTest.java:86)
```

**Comment by jeremy-wendt** [comment]
Weird.  All tests run fine for me (including this one).  The only differences I see between what I've pushed and what I have local is in the millions of nbproject files for the various Netbeans projects.  And looking at the relevant ones, I don't see any real difference (just dependencies getting moved to different lines in the file).  I didn't push these as they change for every different machine you open them on.  Do you want me to add them to this pull request?

This code did have some issues when I first tried merging with your recent changes to MTJ dependencies (or something like that).  I had to change various import dependencies, and then the problems went away.

Any suggestions?

**Comment by jeremy-wendt** [comment]
I do have to set my JAVA_HOME to Java 7 to get any of this to work...  Java 8 has real problems.

**Comment by Zero3** [comment]
Note that Java 7 has been end-of-life for a couple of months already, and thus no longer receives any updates (unless you pay Oracle $$$). Users are thus encouraged to update, and has been served Java 8 through auto-update since January. See https://www.java.com/en/download/faq/java_7.xml for more information.

I don't know which problems with Java 8 you are referring to, but I use Foundry with a Java 8 project. I think it would be a real shame if you broke compatibility with the currently supported version of Java with this PR.

**Comment by jeremy-wendt** [comment]
Hmmm... We've just barely been able to shift to Java7 in the past year due
to some internal complications.  Right now, the Foundry doesn't appear to
have any Java8 code in it... Can we keep it that way w/o keeping Java7 as
the default compiler?

**Comment by Zero3** [comment]
Java should be completely backward compatible, in the sense that you may keep compiling Foundry using a Java 7 compiler and the code will run in any newer Java Runtime Environment (JRE), like the Java 8 JRE.

You can "cross-compile" Java 7 code using the Java 8 compiler with a special command-line flag and a copy of the Java 7 class libraries. This is probably marginally safer from a security standpoint, since you then no longer use a compiler that does not receive any security updates any more.

I was just a little worried that you maybe meant that the code no longer *runs* under Java 8 (which would be pretty bad). I realize now that maybe you meant that the code no longer *compiles* under Java 8 (which would be weird, but acceptable).

**Comment by jeremy-wendt** [comment]
I can't seem to replicate this issue.  I've tried JDK set to 1.7 and 1.8
from the command line.  I've reverted all of the changed properties and xml
files in the nbproject directories.  I'm completely up-to-date on both pull
and push.

The line that shows up as the first in my code with an exception is using
Fields for reflection in a manner that appears consistent with what I see
on line (see http://tutorials.jenkov.com/java-reflection/fields.html at the
bottom where it says that "null" means give me the static final variable.

Can you drop these two lines just before line 144 in NativeBlasHandler?
I'm hoping the printout tells me something...

Thanks,
Jeremy

            Object o = javaBlas.get(null);
            System.out.println(o);

**Comment by jbasilico** [comment]
I got the error both under JDK 1.7 and 1.8 when I ran it through Maven (3.3.1).

I'll try with the changed code.

**Comment by jbasilico** [comment]
It looks like this is trying to change the version of the bindings used by the system. Is this code still needed with the most recent version of MTJ?

**Comment by jbasilico** [comment]
I added those lines of code and the output was: com.github.fommil.netlib.F2jBLAS@383f3558

**Comment by jeremy-wendt** [comment]
This code was altered to match the most recent version of MTJ.  I'll have
to look at the stuff you just sent me.  I have no idea why we're getting
different results.

**Comment by jbasilico** [comment]
This was merged via #56.

**Pull request closed without merging**
